# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/      
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./src/      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./src/      
    - name: Package Release
      run: | 
          dotnet pack -c Release -o ../out
      working-directory: ./src/      
    - name: Publish Nuget to GitHub registry
      run: dotnet nuget push ./out/$(ls ./out) -s https://nuget.pkg.github.com/smuki/index.json -k ${GITHUB_TOKEN}  
      working-directory: ./out/      
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
