# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'           # Push events to every tag not containing /

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Get version
      id: get_version
      run: |
          echo ::save-state name=VERSION::${GITHUB_REF/refs\/tags\//} 
          echo ${{ steps.get_version.outputs.VERSION }}
          echo ${{ github.ref }}
          echo ${{ github.ref }} | cut -d "." -f1,2,3  | cut -d "/" -f3
          
          sed -in-place "s#1.2.3.4#${{ steps.get_version.outputs.VERSION }}#g" ./Volte.Features.csproj  
      working-directory: ./src/          
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/      
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./src/      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./src/      
    - name: Package Release
      run: | 
          dotnet pack -c Release -o ../out
      working-directory: ./src/      
    - name: Publish Nuget to GitHub registry
      run: dotnet nuget push ./*.nupkg -s https://nuget.pkg.github.com/smuki/index.json -k ${{secrets.TOKEN}} --skip-duplicate 
      working-directory: ./out/      
